Vagrant.configure("2") do |config|
  config.vm.define :servidorWeb do |servidorWeb|
  servidorWeb.vm.box = "bento/ubuntu-20.04"
  servidorWeb.vm.network :private_network, ip: "192.168.100.30"
  servidorWeb.vm.hostname = "servidorWeb"
  servidorWeb.vm.provision "shell", path: "scrWEB.sh"
  end
end